module.exports = {
  plugins: ['prettier-plugin-tailwindcss'],
  arrowParens: 'always',
  htmlWhitespaceSensitivity: 'css',
  bracketSameLine: false,
  bracketSpacing: true,
  printWidth: 100,
  proseWrap: 'preserve',
  quoteProps: 'as-needed',
  semi: true,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'all',
  useTabs: false,
  endOfLine: 'auto',
  rangeStart: 0,
  jsxBracketSameLine: false,
  jsxSingleQuote: true,
  requirePragma: false,
  insertPragma: false,
};